# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.6.9"

services:
  - mysql:8.0

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "mirrOS_api_test"
  MYSQL_ROOT_PASSWORD: "glancr"

# Cache gems in between builds
cache:
  paths:
    - vendor/cache

stages:
  - test
  - bundle

before_script:
  - ruby -v                         # Print out ruby version for debugging
  - gem update bundler              # Update bundler to 2.x

# Optional - Delete if not using `rubocop`
# rubocop:
#   script:
#     - rubocop

# Disabled until we're actually using rspec
# rspec:
#   stage: test
#   script:
#    - rspec spec

rails:
  stage: test
  script:
    # Install dependencies into ./vendor/bundle
    - bundle install -j $(nproc) --path vendor/bundle
    - export RAILS_ENV=test
    - export RAILS_DATABASE_HOST=mysql
    - bin/rails db:setup
    # - rails test # disabled until we're actually using tests
