# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.5"

# Cache gems in between builds
cache:
  paths:
    - vendor/cache

stages:
- test
- bundle

before_script:
  - ruby -v                                   # Print out ruby version for debugging
  - gem update bundler                        # Update bundler to 2.x
  - bundle package --all-platforms
#  - bundle install -j $(nproc) --path vendor/bundle  # Install dependencies into ./vendor/bundle

# Optional - Delete if not using `rubocop`
#rubocop:
#  script:
#  - rubocop

# Disabled until we're actually using rspec
#rspec:
#  stage: test
#  script:
#  - rspec spec

rails:
  stage: test
  script:
  - bundle install -j $(nproc) --path vendor/bundle  # Install dependencies into ./vendor/bundle
  - bin/rails db:migrate
  - bin/rails db:seed
  # - rails test # disabled until we're actually using tests
  dependencies: [] # do not pass vendor/bundle to next job since it's x86-specific

zipfile:
  stage: bundle
  script:
  - shopt -s extglob      # enable globbing to simplify mv command
  - git describe --always > build_version
  - mkdir api             # put everything required in subdirectory
  - mv !(api|docs|test) api/
  - mv .ruby-version api/ # only dotfile required by Rails. Do not set dotglob, or mv will attempt to move parent directories

  artifacts:
    paths:
      - api
