require: rubocop-rails
AllCops:
  Exclude:
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 200

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 50
