---
default: &default
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

sqlite: &sqlite
  <<: *default
  adapter: sqlite3
  encoding: unicode

mysql: &mysql
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  socket: <%= ENV.fetch("RAILS_DATABASE_SOCKET") { '/tmp/mysql.sock' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *mysql
  database: mirrOS_api_development
  username: root
  password: glancr

test:
  <<: *sqlite
  database: db/mirrOS_api_test.sqlite3

# NOTE: password provided in cleartext since the snap with env variables is open source as well, so using env
# variables is really a vain attempt at security by obscurity.
production:
  <<: *mysql
  database: mirrOS_api_production
  username: root
  password: glancr
