# Equal amount of threads for sidekiq as for Rails
:concurrency: 3
:queues:
  - system
  - sources
  - default
:dynamic: true
:dynamic_every: 10s
:schedule:
  CheckWiFiSignalJob:
    every: '2m'
    queue: system
    description: 'Checks the WiFi signal strength for the active access point'
  RestartBrowserJob:
    # TODO: This relies on a correct Rails.configuration.timezone
    cron: '0 */8 * * *'
    queue: system
    description: 'Attempts a browser restart every eight hours'
  ScheduleSourceInstancesJob:
    in: '15s'
    queue: system
    description: 'Schedules all existing source instances at startup'
