:dynamic: true
:schedule:
  CheckWiFiSignalJob:
    every: '2m'
    queue: system
    description: 'Checks the WiFi signal strength for the active access point'
  RestartBrowserJob:
    # TODO: This relies on a correct Rails.configuration.timezone
    cron: '0 */8 * * *'
    queue: system
    description: 'Attempts a browser restart every eight hours'
